export enum Gender {
	MALE = 1,
	FEMALE = 2,
}

export enum BussinessType {
	B2B = 'B2B',
	B2C = 'B2C',
}

export enum IndustryType {
	SPINNING = 'SPINNING',
	WEAVING = 'WEAVING',
	KNITTING = 'KNITTING',
	YARN_PROCESSING = 'YARN_PROCESSING',
	FABRIC_PROCESSING = 'FABRIC_PROCESSING',
	GARMENT_MANUFACTURING = 'GARMENT_MANUFACTURING',
}
